### PR TITLE
Update SBOM build information

### PR DESCRIPTION
**Pull request by vargenau**
Signed-off-by: Marc-Etienne Vargenau <marc-etienne.vargenau@nokia.com>

### CODE REVIEW

**Review by Jimmy-ahlberg — COMMENTED** [review]
WE need to have a much bigger conversation on WHEN is an SBOM created, the current wording is unclear and creates obligations with much uncertainty.

**Comment by winterrocks** [comment]
I'm not sure if it is possible to mandate all vendors to create SBOM at some time. But likely build time is the best?

**Comment by stephenkilbaneadi** [comment]
Oh, every vendor has to create an SBOM at _some_ time - no vendor will create one at _no_ time. :-)

But this isn't about requiring that all vendors create the SBOM at the same point in the build process, but that they record in the SBOM the choice the vendor made.

**Comment by eaglei15** [comment]
6CFEF42E-61DA-4ED9-87DF-BB03E1298143

**Pull request closed without merging**
